### PR TITLE
tests + announce notification fix

### LINKED ISSUE #170: [bug] Reblog/boost notifications not working
https://github.com/superseriousbusiness/gotosocial/pull/148 seems to have broken Reblog/Boost notifications from being created -- we need to investigate why, and write some tests for this behavior.

### PR DESCRIPTION
**Pull request by tsmethurst**
This PR fixes a tiny issue with reblog/boost notifications not being created (replacing `==` with `!=` in one file -- https://github.com/superseriousbusiness/gotosocial/pull/193/files#diff-4702c34f947db9e2ac6ce9f82430f5ac32d518f76ba4dc3e9963383a2d2f9499R255), and adds some tests to validate that notifications are created when a boost/reblog is processed.

It also adds a couple of tests elsewhere, and tidies up some existing tests.

closes #170

### CODE REVIEW

File: internal/db/bundb/bundb_test.go [hunk 1]
```diff
@@ -44,3 +45,27 @@ type BunDBStandardTestSuite struct {
 	testTags         map[string]*gtsmodel.Tag
 	testMentions     map[string]*gtsmodel.Mention
 }
+
+func (suite *BunDBStandardTestSuite) SetupSuite() {
```
Comment (NyaaaWhatsUpDoc) [inline internal/db/bundb/bundb_test.go:49]: ah this was a change i had in mind for a while now, much neater :D

File: internal/processing/fromcommon.go [hunk 2]
```diff
@@ -254,7 +252,7 @@ func (p *processor) notifyAnnounce(ctx context.Context, status *gtsmodel.Status)
 		status.BoostOfAccount = boostedAcct
 	}
 
-	if status.BoostOfAccount.Domain == "" {
+	if status.BoostOfAccount.Domain != "" {
```
Comment (NyaaaWhatsUpDoc) [inline internal/processing/fromcommon.go:255]: oh damn, this is a silly one :sweat_smile:

**Review by NyaaaWhatsUpDoc — APPROVED** [review]
