### PR TITLE
[bugfix] 2643 bug search for account url doesnt always work when redirected

### LINKED ISSUE #2643: [bug] Search for account URL doesn't always work when redirected
### Describe the bug with a clear and concise description of what the bug is.

Pixelfed seems to generate three different URLs for a post:

1. The URL a logged in user sees when opening a post from the Local feed (i.e. https://pixelfed.de/i/web/post/${ID})
2. When clicking the timestamp from the above point, the Post opens in a different interface and the URL becomes https://pixelfed.de/p/${USER}/${ID}?fs=1
3. The canonical URL for a Post https://pixelfed.de/p/${USER}/${ID}

Note especially the `?fs=1` parameter being the only difference between 2 and 3.

### What's your GoToSocial Version?

0.13.3

### GoToSocial Arch

arm64 Binary

### What happened?

When pasting URLs 1. and 2. into the Search on a GTS account, the post cannot be found and errors are logged:
```
# URL type 1 fails
Feb 16 10:44:00 hal9000 gotosocial[32056]: func=search.(*Processor).Get level=DEBUG maxID="" minID="" limit='5' offset='0' query=https://pixelfed.de/i/web/post/663854260074423729 queryType="" resolve=true following=false requestID=54mmvccd04001bqdt2vg msg="beginning search"
Feb 16 10:44:00 hal9000 gotosocial[32056]: func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://pixelfed.de/i/web/post/663854260074423729 requestID=54mmvccd04001bqdt2vg pubKeyID=https://boosts.squirrel.pictures/users/fl4nn/main-key msg="performing request"
Feb 16 10:44:00 hal9000 gotosocial[32056]: func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://pixelfed.de/i/web/post/663854260074423729 requestID=54mmvccd04001bqdt2vg pubKeyID=https://boosts.squirrel.pictures/users/fl4nn/main-key msg="performing request"
Feb 16 10:44:00 hal9000 gotosocial[32056]: func=server.glob..func1.Logger.func13.1 level=ERROR latency=141.587573ms userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0" method=GET statusCode=500 path=/api/v2/search clientIP=192.168.1.222 errors="Error #01: Get: error searching by URI: byURI: error looking up https://pixelfed.de/i/web/post/663854260074423729 as status: enrichStatus: dereferenced status uri https://pixelfed.de/p/defernite/663854260074423729 does not match https://pixelfed.de/i/web/post/663854260074423729\n" requestID=54mmvccd04001bqdt2vg msg="Internal Server Error: wrote 54B"


# URL type 2 fails
Feb 16 10:45:10 hal9000 gotosocial[32056]: func=search.(*Processor).Get level=DEBUG maxID="" minID="" limit='5' offset='0' query=https://pixelfed.de/p/defernite/663855289106142950?fs=1 queryType="" resolve=true following=false requestID=a0wmxccd040000ry7700 msg="beginning search"
Feb 16 10:45:10 hal9000 gotosocial[32056]: func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://pixelfed.de/p/defernite/663855289106142950?fs=1 requestID=a0wmxccd040000ry7700 pubKeyID=https://boosts.squirrel.pictures/users/fl4nn/main-key msg="performing request"
Feb 16 10:45:10 hal9000 gotosocial[32056]: func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://pixelfed.de/p/defernite/663855289106142950?fs=1 requestID=a0wmxccd040000ry7700 pubKeyID=https://boosts.squirrel.pictures/users/fl4nn/main-key msg="performing request"
Feb 16 10:45:10 hal9000 gotosocial[32056]: func=server.glob..func1.Logger.func13.1 level=ERROR latency=97.662604ms userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0" method=GET statusCode=500 path=/api/v2/search clientIP=192.168.1.222 errors="Error #01: Get: error searching by URI: byURI: error looking up https://pixelfed.de/p/defernite/663855289106142950?fs=1 as status: enrichStatus: dereferenced status uri https://pixelfed.de/p/defernite/663855289106142950 does not match https://pixelfed.de/p/defernite/663855289106142950?fs=1\n" requestID=a0wmxccd040000ry7700 msg="Internal Server Error: wrote 54B"


# URL type 3 (canonical) succeeds
Feb 16 10:45:55 hal9000 gotosocial[32056]: func=search.(*Processor).Get level=DEBUG maxID="" minID="" limit='5' offset='0' query=https://pixelfed.de/p/defernite/663855289106142950 queryType="" resolve=true following=false requestID=vfn4xccd04001gb43s80 msg="beginning search"
Feb 16 10:45:55 hal9000 gotosocial[32056]: func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://pixelfed.de/p/defernite/663855289106142950 requestID=vfn4xccd04001gb43s80 pubKeyID=https://boosts.squirrel.pictures/users/fl4nn/main-key msg="performing request"
Feb 16 10:45:55 hal9000 gotosocial[32056]: func=server.glob..func1.Logger.func13.1 level=INFO latency=44.18858ms userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0" method=GET statusCode=200 path=/api/v2/search clientIP=192.168.1.222 requestID=vfn4xccd04001gb43s80 msg="OK: wrote 1.33kiB"
```
Only the canonical URL is accepted to look up the post.

### What you expected to happen?

The post can be looked up by any of the URLs.

### How to reproduce it?

1. Be logged in on a Pixelfed instance, open any post from the Local feed -> the URL bar shows a URL type 1
2. Click on the Timestamp of the Post, it will show the Post in a different interface, possibly the one non-logged in users would get, the URL bar shows a URL type 2
3. Right clicking the Timestamp and selecting "Copy link" will give you the canonical URL (Type 3) at any point

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by NyaaaWhatsUpDoc**
# Description

- updates our fork of `go-fed/activity` to update the Dereferencer() to return the full http.Response{} object
- updates our dereferencer to perform AS object URI ID vs. location checks against the final URL, which allows for dereferencing objects with redirects
- updates our use of json.NewDecoder(...).Decode() to perform a final "empty" decode after primary attempt, to ensure there is no more garbage / extra data remaining in reader after provided JSON (thanks @daenney for the long back-and-forth with code examples we had on this :grin:) 

closes #2643

~~Draft until https://github.com/superseriousbusiness/activity/pull/21 is merged.~~

MUST BE **SQUASHED** AND MERGED TO ENSURE THE EMBEDDED `./activity` FOLDER DOESN'T GET INCLUDED IN THE REPO GIT HISTORY.

## Checklist

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [ ] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by NyaaaWhatsUpDoc** [comment]
Testing using `https://pixelfed.de/i/web/post/663855289106142950` I can confirm that the redirected post is successfully loaded (and accessible using the correct final location URI).

File: internal/federation/dereferencing/announce.go [hunk 1]
```diff
@@ -83,6 +83,10 @@ func (d *Dereferencer) EnrichAnnounce(
 		return nil, gtserror.Newf("error generating id: %w", err)
 	}
 
+	// Set boost_of_uri again in case the
+	// original URI was an indirect link.
+	boost.BoostOfURI = target.URI
```
Comment (NyaaaWhatsUpDoc) [inline internal/federation/dereferencing/announce.go:88]: this here is important

File: internal/federation/dereferencing/account.go [hunk 2]
```diff
@@ -567,20 +567,52 @@ func (d *Dereferencer) enrichAccount(
...
+			// ResolveAccountable will set gtserror.WrongType
 			// on the returned error, so we don't need to do it here.
-			err = gtserror.Newf("error resolving accountable from data for account %s: %w", uri, err)
+			err = gtserror.Newf("error resolving accountable %s: %w", uri, err)
 			return nil, nil, err
 		}
+
+		// Check whether input URI and final returned URI
+		// have changed (i.e. we followed some redirects).
+		if finalURIStr := rsp.Request.URL.String(); //
```
Comment (NyaaaWhatsUpDoc) [inline internal/federation/dereferencing/account.go:591]: also important here, if we followed a redirect we need to recheck the database and update the uri model we check against later

File: internal/federation/dereferencing/status.go [hunk 3]
```diff
@@ -393,16 +393,51 @@ func (d *Dereferencer) enrichStatus(
...
-			return nil, nil, gtserror.Newf("error resolving statusable from data for account %s: %w", uri, err)
+			// ResolveStatusable will set gtserror.WrongType
+			// on the returned error, so we don't need to do it here.
+			err = gtserror.Newf("error resolving statusable %s: %w", uri, err)
+			return nil, nil, err
+		}
+
+		// Check whether input URI and final returned URI
+		// have changed (i.e. we followed some redirects).
+		if finalURIStr := rsp.Request.URL.String(); //
```
Comment (NyaaaWhatsUpDoc) [inline internal/federation/dereferencing/status.go:417]: also important here, if we followed a redirect we need to recheck the database and update the uri model we check against later

File: internal/federation/dereferencing/thread.go [hunk 4]
```diff
@@ -384,3 +394,26 @@ stackLoop:
 
 	return gtserror.Newf("reached %d descendant iterations for %q", maxIter, statusIRIStr)
 }
+
+// updateStatusParent updates the given status' parent
+// status URI, ID and account ID to given values in DB.
+func (d *Dereferencer) updateStatusParent(
```
Comment (NyaaaWhatsUpDoc) [inline internal/federation/dereferencing/thread.go:400]: this just helps neaten up the dereferenceStatusAncestors() function that no matter my attempts always seems to end up sprawling :sob:

File: internal/federation/dereferencing/thread.go [hunk 5]
```diff
@@ -33,7 +33,7 @@ import (
 
 // maxIter defines how many iterations of descendants or
 // ancesters we are willing to follow before returning error.
-const maxIter = 1000
+const maxIter = 512
```
Comment (NyaaaWhatsUpDoc) [inline internal/federation/dereferencing/thread.go:36]: honestly 1000 is a bit too excessive. i think 512 as a maximum depth is a *bit* more reasonable :p

File: internal/federation/dereferencing/thread.go (hunk 4 above)
Comment (NyaaaWhatsUpDoc) [reply internal/federation/dereferencing/thread.go:400]: why must there be so many edge cases ...

File: internal/ap/collections.go [hunk 6]
```diff
@@ -26,6 +26,24 @@ import (
 	"github.com/superseriousbusiness/gotosocial/internal/paging"
 )
 
+// TODO: replace must of this logic with just
```
Comment (NyaaaWhatsUpDoc) [inline internal/ap/collections.go:29]: i started work on this but i'll save it for another PR. basically we can remove a bunch of this extra iterator wrapping code here and deal with the collection (page) like objects in a more similar manner to the other IRI iterators we have in the properties.go source file

File: internal/federation/dereferencing/account.go [hunk 7]
```diff
@@ -1108,20 +1097,21 @@ func (d *Dereferencer) dereferenceAccountFeatured(ctx context.Context, requestUs
...
 
-		// If the status was already pinned, we don't need to do anything.
+		// If the status was already pinned,
+		// we don't need to do anything.
 		if !status.PinnedAt.IsZero() {
 			continue
 		}
 
-		if status.AccountID != account.ID {
+		if status.AccountURI != account.URI {
```
Comment (NyaaaWhatsUpDoc) [inline internal/federation/dereferencing/account.go:1106]: i updated to use URI checks here, just as the URI IDs are a little more robust / consistent than our database IDs

File: internal/federation/dereferencing/thread.go (hunk 5 above)
Comment (mirabilos) [reply internal/federation/dereferencing/thread.go:36]: I’ll let you know when a Polymaths thread gets more than this many posts in a chain…

**Comment by daenney** [comment]
I think this looks good. The collection bits is honestly going a little over my head.

File: internal/transport/controller.go [hunk 8]
```diff
@@ -150,36 +155,73 @@ func (c *controller) NewTransportForUsername(ctx context.Context, username strin
...
+		return nil, err
+	}
+
+	// Return a response with AS data as body.
+	rsp := craftResponse(iri, http.StatusOK)
+	rsp.Body = io.NopCloser(bytes.NewReader(b))
+	return rsp, nil
+}
+
+func craftResponse(url *url.URL, code int) *http.Response {
```
Comment (tsmethurst) [inline internal/transport/controller.go:218]: Do we need to set appropriate content-type etc on these crafted responses?

File: internal/federation/dereferencing/thread.go [hunk 9]
```diff
@@ -153,49 +155,57 @@ func (d *Dereferencer) DereferenceStatusAncestors(ctx context.Context, username
...
+		// are possible with / without
+		// any returned error.
+		switch {
+
+		// The current status is using an indirect URL
+		// in order to reference the parent. This is just
+		// weird and broken... Leave the URI in place but
+		// don't link the statuses via database IDs as it
+		// could cause all sorts of unexpected situations.
+		case current.InReplyToURI != parent.URI:
```
[the remark this answers is not in the document]
Comment (tsmethurst) [reply internal/federation/dereferencing/thread.go:192]: Good thinking.

File: internal/federation/dereferencing/thread.go (hunk 4 above)
Comment (tsmethurst) [reply internal/federation/dereferencing/thread.go:400]: It's complex isn't it :P

File: internal/federation/dereferencing/thread.go [hunk 10]
```diff
@@ -153,49 +155,57 @@ func (d *Dereferencer) DereferenceStatusAncestors(ctx context.Context, username
 		// the now-gone parent.
 		case code == http.StatusGone:
 			l.Trace("status orphaned")
-			current.InReplyToID = ""
-			current.InReplyToURI = ""
-			current.InReplyToAccountID = ""
-			current.InReplyTo = nil
```
Comment (tsmethurst) [inline internal/federation/dereferencing/thread.go:159]: Is there any chance this InReplyTo (status) could be set as a stub or anything like that? Just checking.

File: internal/ap/collections.go (hunk 6 above)
Comment (tsmethurst) [reply internal/ap/collections.go:29]: Alright, no worries. For now it would be good if there were some tests specifically for these wrapping functions, just to make sure everything works with them as expected. Would you mind writing some?

File: internal/ap/resolve.go [hunk 11]
```diff
@@ -213,3 +158,94 @@ func ResolveAccountable(ctx context.Context, b []byte) (Accountable, error) {
...
+var emptydest = &struct{}{}
+
+// decodeType tries to read and parse the data
+// at provided io.Reader as a JSON ActivityPub
+// type, failing if not parseable as JSON or not
+// resolveable as one of our known AS types.
+//
+// The given map pointer will also be populated with
+// the 'raw' JSON data, for further processing.
+func decodeType(
```
Comment (tsmethurst) [inline internal/ap/resolve.go:216]: I wonder, since we're done with the response body at this point, is it worth type checking here to see if it's a closer, and closing it so the caller doesn't have to bother? Or are there cases where callers still need to access the response body for whatever reason?

File: internal/federation/dereferencing/account.go [hunk 12]
```diff
@@ -1108,20 +1097,21 @@ func (d *Dereferencer) dereferenceAccountFeatured(ctx context.Context, requestUs
...
 			// Someone's pinned a status that doesn't
 			// belong to them, this doesn't work for us.
 			continue
 		}
 
-		if status.BoostOfID != "" {
-			// Someone's pinned a boost. This also
-			// doesn't work for us.
+		if status.BoostOfURI != "" {
```
Comment (tsmethurst) [inline internal/federation/dereferencing/account.go:1112]: Be very careful using BoostOfURI here -- that's one of the fields that's not inserted into the database, it's just added to the status sometimes. Might be better to continue using BoostOfID here.

File: internal/federation/dereferencing/announce.go (hunk 1 above)
Comment (NyaaaWhatsUpDoc) [reply internal/federation/dereferencing/announce.go:88]: indeed :)

File: internal/federation/dereferencing/account.go (hunk 12 above)
Comment (NyaaaWhatsUpDoc) [reply internal/federation/dereferencing/account.go:1112]: oh good point!

File: internal/ap/resolve.go (hunk 11 above)
Comment (NyaaaWhatsUpDoc) [reply internal/ap/resolve.go:216]: i think all instances pass in a closer here so i could just update the type to be a closer and ensure it's closed in here

File: internal/federation/dereferencing/thread.go (hunk 10 above)
Comment (NyaaaWhatsUpDoc) [reply internal/federation/dereferencing/thread.go:159]: hmm good point, i shall have a thonk

File: internal/ap/resolve.go (hunk 11 above)
Comment (tsmethurst) [reply internal/ap/resolve.go:216]: Aha OK, we might as well do that then :) That seems fine to me if the response body is always closed immediately after calling + returning from this function anyway.

Comment (NyaaaWhatsUpDoc) [reply internal/ap/resolve.go:221]: see: 289b956f2

Comment (tsmethurst) [reply internal/ap/resolve.go:221]: Great :)

File: internal/federation/dereferencing/account.go (hunk 12 above)
Comment (NyaaaWhatsUpDoc) [reply internal/federation/dereferencing/account.go]: fixed that here: 02c1d7183

File: internal/federation/dereferencing/thread.go (hunk 10 above)
Comment (NyaaaWhatsUpDoc) [reply internal/federation/dereferencing/thread.go:159]: have updated here: 36c44806f

**Comment by tsmethurst** [comment]
I *think* this will close https://github.com/superseriousbusiness/gotosocial/issues/2327 as well, but we'll have to check.

File: internal/ap/collections.go (hunk 6 above)
Comment (NyaaaWhatsUpDoc) [reply internal/ap/collections.go:29]: added tests for them here: 452e9fd56

**Comment by NyaaaWhatsUpDoc** [comment]
> I _think_ this will close #2327 as well, but we'll have to check.

do you have any examples of this i can check on my instance that's running this patch rn? :thinking:
