### PR TITLE
[bugfix] Don't throw error when parent statuses are missing (#2011)

### LINKED ISSUE #2011: [bug] unable to interact (including delete) post after delete-and-redraft parent + 500 ISE
### Describe the bug with a clear and concise description of what the bug is.

I’ve written a post (in a direct message), then replied to that, then later delete-and-redraft-ed the first one.

This now leads to severe misbehaviour:

One, it’s still in my Semaphore timeline, but I cannot delete it (“404”, but the log does not show the ID of the post itself but probably the one of its now-gone parent).

Two, if I zoom on it in Semaphore, I get “internet access failed, showing offline content”.

Three, if I start a new Semaphore in a new tab, then search for the toot URL copied from the other tab, I get a 500:

    timestamp="21/07/2023 00:22:39.122" func=middleware.Logger.func1.1 level=ERROR latency=28.552173ms userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" method=GET statusCode=500 path=/api/v2/search error="Error #01: packageStatuses: error checking visibility of status 01H5TPKZC51NA28WE3822PS62F for account 01GS55SW7VWYN3BFRYCX5NW526: isStatusVisible: error populating status 01H5TPKZC51NA28WE3822PS62F: \"error populating status parent: no entries\",\"error populating status parent: no entries\"\n" requestID=yq0d6xc90400048tbnhg msg="Internal Server Error: wrote 54B"

### What's your GoToSocial Version?

0.10.0-rc3 git-f431974

### GoToSocial Arch

amd64 binary

### What happened?

_No response_

### What you expected to happen?

I’m **fully** expecting to be able to do **any and all** interaction with any status I posted myself, independent of what happened to any other toot, related or not.

This includes parent being gone (deleted (redrafted or not)), parent not being visible to me any more because the parent’s author blocked or fediblocked me or I blocked or fediblocked them, or because the instance of the parent is gone or no longer reachable or suddenly serves http on the https port (don’t laugh, it happened to one (`hubzilla.eu`) which I saw watching the log today).

### How to reproduce it?

I assume posting, replying, then deleting the first post will do.

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by snowkat**
# Description

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
>
> If this is a documentation change, please briefly describe what you've changed and why.

This pull request allows retrieving posts that reply to a parent status that isn't in the database, by ending the traversal below the missing parent. A missing parent post can happen for a few reasons: the calling user being blocked, a deleted post, or federation/remote server issues come to mind.

closes #2011

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [X] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [X] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [X] I/we have not leveraged AI to create the proposed changes.
- [X] I/we have performed a self-review of added code.
- [X] I/we have written code that is legible and maintainable by others.
- [X] I/we have commented the added code, particularly in hard-to-understand areas.
- [X] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [X] I/we have run tests and they pass locally with the changes.
- [X] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

**Comment by snowkat** [comment]
As an aside: I tried adding a test to status_test.go, but that requires updating testrig/testmodels.go in a way that breaks multiple other tests. If there's better way to go about adding statuses outside of `NewTestStatuses()`, I can build a test for this case.

**Comment by tsmethurst** [comment]
I think this is probably OK as a *temporary* fix until we have #2058 in place to handle this properly. @NyaaaWhatsUpDoc do you have any onions?

File: internal/db/bundb/status.go [hunk 1]
```diff
@@ -562,6 +562,12 @@ func (s *statusDB) GetStatusParents(ctx context.Context, status *gtsmodel.Status
 	for id := status.InReplyToID; id != ""; {
 		parent, err := s.GetStatusByID(ctx, id)
 		if err != nil {
+			if errors.Is(err, db.ErrNoEntries) {
```
Comment (NyaaaWhatsUpDoc) [inline internal/db/bundb/status.go:565]: alternatively how do you feel about doing:

```golang
parent, err := s.GetStatusByID(ctx, id)
if err != nil && !errors.Is(err, db.ErrNoEntries) {
    return nil, err
}

if parent == nil {
    break
}
```

it just makes it a bit clearer this isn't so much an error condition and more to be expected, as yeah we should have been handling this given how we handle deleting statuses

**Comment by NyaaaWhatsUpDoc** [comment]
great work, thanks! just the one comment from me :)

File: internal/db/bundb/status.go (hunk 1 above)
Comment (snowkat) [reply internal/db/bundb/status.go]: Makes sense to me!
