### PR TITLE
[bugfix/chore] Refactor timeline code

### LINKED ISSUE #1600: [bug] Timeline just ends, prepareBehind: error preparing item with id
### Describe the bug with a clear and concise description of what the bug is.

Load my home timeline on a non-caching front-end (like, e.g., elk or pinafore). The timeline just ends, sometimes, and GoToSocial then prints something like
```
timestamp="07/03/2023 11:51:40.134" func=timeline.(*manager).GetTimeline level=ERROR timelineAccountID=<accountId> msg="error getting statuses: prepareBehind: error preparing item with id <itemId>: statusPrepareFunction: error getting status with id <itemId>"
```

Given that it happens on at least two different clients, I think this might be an issue with GoToSocial. I do not know when it happens or how to trigger it, unfortunately.

### What's your GoToSocial Version?

 GoToSocial 0.7.0 git-b599309

### GoToSocial Arch

_No response_

### What happened?

The timeline ends, GoToSocial prints an error.

### What you expected to happen?

The timeline to go on.

### How to reproduce it?

Unknown

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by tsmethurst**
# Description

> If this is a code change, please include a summary of what you've coded, and link to the issue(s) it closes/implements.
>
> If this is a documentation change, please briefly describe what you've changed and why.

This pull request refactors the timeline code for readability, bug fixes, and performance:

- Allow proper paging up using minID.
- Only use one linked list for timeline, instead of two separate ones.
- Only fail when preparing on proper database errors -- closes #1600 
- Reduce duplicated code.
- Remove unused functions.

## Checklist

Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> `[x]`

If this is a documentation change, only the first checkbox must be filled (you can delete the others if you want).

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [x] I/we have made any necessary changes to documentation.
- [x] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

File: internal/timeline/types.go [hunk 1]
```diff
@@ -17,10 +17,18 @@
...
+// Timelineable represents any item that can be indexed in a timeline.
 type Timelineable interface {
 	GetID() string
 	GetAccountID() string
 	GetBoostOfID() string
 	GetBoostOfAccountID() string
 }
+
+// Preparable represents any item that can be prepared in a timeline.
+type Preparable interface {
```
Comment (NyaaaWhatsUpDoc) [inline internal/timeline/types.go:29]: is it worth having a separate interface containing the same methods? maybe a slightly more generic interface name that would fit both object types :thinking:

Comment (tsmethurst) [reply internal/timeline/types.go:29]: Yeah good point! Will change it

File: internal/processing/fromcommon.go [hunk 2]
```diff
@@ -455,8 +455,8 @@ func (p *Processor) timelineStatusForAccount(ctx context.Context, account *gtsmo
 		return nil
 	}
 
-	// stick the status in the timeline for the account and then immediately prepare it so they can see it right away
-	if inserted, err := p.statusTimelines.IngestAndPrepare(ctx, status, account.ID); err != nil {
+	// stick the status in the timeline for the account
+	if inserted, err := p.statusTimelines.IngestOne(ctx, account.ID, status); err != nil {
```
Comment (tsmethurst) [inline internal/processing/fromcommon.go:459]: note for reviewer(s):

this now always prepares the entry as it's being inserted, since we weren't really using the other function anyways

File: internal/processing/statustimeline.go [hunk 3]
```diff
@@ -174,37 +178,54 @@ func (p *Processor) HomeTimelineGet(ctx context.Context, authed *oauth.Auth, max
...
-	prevMinIDValue := ""
-	for i, item := range filtered {
+	var (
+		items          = make([]interface{}, 0, count)
+		nextMaxIDValue string
+		prevMinIDValue string
+	)
+
+	for i, s := range statuses {
+		// Set next + prev values before filtering and API
```
Comment (tsmethurst) [inline internal/processing/statustimeline.go:202]: note for reviewer(s):

this change ensures that the caller always uses the outside range of returned statuses, before they're filtered

previously, if the public timeline db call returned, say, 10 statuses, and 8 from the end got filtered out, the next maxID would be set to only the second status in the slice, meaning that the NEXT call to this function would then include the 8 statuses that were filtered out, causing unnecessary db calls + wasteful checks

the tradeoff here is that now we expose IDs of statuses in the Link headers that the caller doesn't want to see; but since these are public statuses, it's not really a big deal imo

File: internal/timeline/index.go [hunk 4]
```diff
@@ -24,103 +24,205 @@ import (
...
 
-	// now check if the length of indexed items exceeds the amount of items required (position of itemID, plus amount of posts requested after that)
-	if t.indexedItems.data.Len() > position+amount {
-		// we have enough indexed behind already to satisfy amount, so don't need to make db calls
-		l.Trace("returning nil since we already have enough items indexed")
-		return nil
+	// We can now figure out if we need to make db calls.
+	var grabMore bool
+	switch {
+	case listLen < amount:
```
Comment (tsmethurst) [inline internal/timeline/index.go:103]: note for reviewer(s):

There's likely a better way of doing this and/or more conditions that need to be checked.

File: internal/timeline/index.go [hunk 5]
```diff
@@ -24,103 +24,205 @@ import (
...
+			// Page up.
+			minID = items[0].GetID()
+			if minID >= behindID {
+				// Can't go any further.
+				break
+			}
+		}
+
+		for _, item := range items {
+			ok, err := t.filterFunction(ctx, t.accountID, item)
```
Comment (tsmethurst) [inline internal/timeline/index.go:208]: Here's where that pesky filter function is called (see above comment)

File: internal/timeline/manager.go [hunk 6]
```diff
@@ -97,31 +100,41 @@ type manager struct {
...
-	// range through all timelines in the sync map once per hour + prune as necessary
+	// Start a background goroutine which iterates
+	// through all stored timelines once per hour,
+	// and cleans up old entries if that timeline
+	// hasn't been accessed in the last hour.
 	go func() {
 		for now := range time.NewTicker(1 * time.Hour).C {
-			m.accountTimelines.Range(func(key any, value any) bool {
-				timelineAccountID, ok := key.(string)
+			// Define the range function inside here,
```
Comment (tsmethurst) [inline internal/timeline/manager.go:109]: note for reviewer(s):

I wrote and rewrote this bit of code a couple of times to try to find the neatest way of doing it. I'm not 100% happy with the result; there's likely a nicer way of doing it.

File: internal/db/bundb/timeline.go [hunk 7]
```diff
@@ -56,11 +59,9 @@ func (t *timelineDB) GetHomeTimeline(ctx context.Context, accountID string, maxI
 			bun.Ident("follow.target_account_id"),
 			bun.Ident("status.account_id"),
 			bun.Ident("follow.account_id"),
-			accountID).
-		// Sort by highest ID (newest) to lowest ID (oldest)
-		Order("status.id DESC")
+			accountID)
 
-	if maxID == "" {
+	if maxID == "" || maxID == id.Highest {
```
Comment (NyaaaWhatsUpDoc) [inline internal/db/bundb/timeline.go:64]: I'd make this `|| maxID >= id.Highest`

Comment (NyaaaWhatsUpDoc) [reply internal/db/bundb/timeline.go:64]: actually don't worry i'll catch this
