### PR TITLE
[bugfix] don't accept unrelated statuses 

### LINKED ISSUE #1965: [bug] Federation with wafrn is weird
### Describe the bug with a clear and concise description of what the bug is.

Posts from [wafrn](https://app.wafrn.net/) show up in the federated timeline despite not being related to any follows.

### What's your GoToSocial Version?

v0.9.0

### GoToSocial Arch

armv7 Binary

### What happened?

Nobody on our instance follows anybody on app.wafrn.net, or vice-versa. But somehow many of the posts from app.wafrn.net show up in our federated timeline, and also many of the posts *interacted with* by people at app.wafrn.net show up there too.

### What you expected to happen?

Probably none of their posts or posts they interact with should be in our federated timeline unless we follow them.

### How to reproduce it?

federating with app.wafrn.net seems to be enough

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by NyaaaWhatsUpDoc**
# Description
Updates federatingdb logic to only accept status creation activities if the receiving account is either mentioned, or follows the requesting account.  Also reshuffles the `createStatusable()` logic a little so we check for an existing status with URI in the database before bothering with the deref of forwarded status.

closes #1965

## Checklist
- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [ ] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [ ] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

File: internal/federation/federatingdb/create.go [hunk 1]
```diff
@@ -116,134 +118,194 @@ func (f *federatingDB) activityBlock(ctx context.Context, asType vocab.Type, rec
...
 	}
 
-	// create should have an object
-	object := create.GetActivityStreamsObject()
-	if object == nil {
-		return errors.New("Create had no Object")
+	// Create must have an Object.
+	objectProp := create.GetActivityStreamsObject()
+	if objectProp == nil {
+		return gtserror.New("Create had no Object")
```
Comment (daenney) [inline internal/federation/federatingdb/create.go:138]:
```suggestion
		return gtserror.New("create had no Object")
```

File: internal/federation/federatingdb/create.go [hunk 2]
```diff
@@ -116,134 +118,194 @@ func (f *federatingDB) activityBlock(ctx context.Context, asType vocab.Type, rec
...
+	// for this statusable, based on the ID/URI.
+	statusableURIStr := statusableURI.String()
+	status, err := f.state.DB.GetStatusByURI(ctx, statusableURIStr)
+	if err != nil && !errors.Is(err, db.ErrNoEntries) {
+		return gtserror.Newf("db error checking existence of status %s: %w", statusableURIStr, err)
+	}
+
+	if status != nil {
+		// We already had this status in the
+		// db, no need for further action.
```
Comment (daenney) [inline internal/federation/federatingdb/create.go:219]: Should we log this fact at debug level?

File: internal/processing/fromfederator.go [hunk 3]
```diff
@@ -108,26 +109,46 @@ func (p *Processor) ProcessFromFederator(ctx context.Context, federatorMsg messa
...
 	}
 
 	if err != nil {
 		return gtserror.Newf("error extracting status from federatorMsg: %w", err)
 	}
 
+	// Before we go whacking this status in our db, ensure
+	// it's actually relevant to the account who received it
+	// in their Inbox, and it's not just a status randomly
+	// blasted at us from somewhere we don't care about.
```
Comment (daenney) [inline internal/processing/fromfederator.go:137]: I think this comment block is in the wrong place. We don't seem to be performing this check here, but instead is done in `createStatusable`?

**Review by daenney — COMMENTED** [review]
Did a first pass, some very minor comments. This all looks really awesome!

File: internal/processing/fromfederator.go (hunk 3 above)
Comment (NyaaaWhatsUpDoc) [reply internal/processing/fromfederator.go:137]: Ah yep that's a case of this being a branch tobi passed to me and i worked from :sweat_smile: i might consider moving the `shouldAcceptStatus()` to here instead actually

File: internal/federation/federatingdb/create.go (hunk 1 above)
Comment (NyaaaWhatsUpDoc) [reply internal/federation/federatingdb/create.go:138]: holy shit github does suggestions now?! i loved this at my old company that used bitbucket

Comment (daenney) [reply internal/federation/federatingdb/create.go:138]: Oh yeah. They added that a while ago but it's really flown under the radar. When you start a comment, the first icon in the bar is a thing that looks like a piece of paper with a plus and minus sign in it. If you click it, it adds this:

````
```suggestion
		return gtserror.New("Create had no Object")
```
````

Then you can edit that and it shows up as a diff/suggestion you can accept.

**Comment by tsmethurst** [comment]
lgtm!

**Review by daenney — APPROVED** [review]
What tobi said!
