### PR TITLE
[bugfix] relax missing preferred_username, instead using webfingered username

### LINKED ISSUE #2961: [bug] Can't find @demo@seppo.social to follow
### Describe the bug with a clear and concise description of what the bug is.

@gerben@nlnet.nl reported to me that he can't find and follow @demo@seppo.social on their gotosocial.

To investigate, I installed https://www.freshports.org/net-im/gotosocial/, configured https://gotosocial.dev.seppo.social/ and checked https://seppo.social/demo/apchk.cgi/webfinger?redirect=self&resource=@demo@gotosocial.dev.seppo.social

The gotosocial server log say
```
$ tail -f /var/log/messages
Jun  4 10:50:20 vmd32118 gotosocial[53222]: timestamp="2024-06-04T10:50:20.267+02:00" func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://seppo.social/demo/apchk.cgi/actor.jsa#main-key requestID=0dc7d70f-753d-44ec-9c5c-1c8e97048399 pubKeyID=https://gotosocial.dev.seppo.social/users/demo/main-key msg="performing request"
Jun  4 10:50:25 vmd32118 gotosocial[53222]: timestamp="2024-06-04T10:50:25.278+02:00" func=server.glob..func1.Logger.func13.1 level=ERROR latency="5.023752519s" userAgent=Seppo.Social method=GET statusCode=500 path=/users/demo clientIP=81.28.232.73 pubKeyID=https://seppo.social/demo/apchk.cgi/actor.jsa#main-key errors="Error #01: callForPubKey: error dereferencing public key https://seppo.social/demo/apchk.cgi/actor.jsa#main-key: Get \"https://seppo.social/demo/apchk.cgi/actor.jsa#main-key\": context deadline exceeded (Client.Timeout exceeded while awaiting headers) (fast fail)\n" requestID=0dc7d70f-753d-44ec-9c5c-1c8e97048399 msg="Internal Server Error: wrote 33B"
```

while https://seppo.social/demo/apchk.cgi/actor.jsa#main-key returns the actor profile json.

### What's your GoToSocial Version?

0.14.1_2

### GoToSocial Arch

FreeBSD binary

### What happened?

```
$ tail -f /var/log/messages
Jun  4 10:50:20 vmd32118 gotosocial[53222]: timestamp="2024-06-04T10:50:20.267+02:00" func=httpclient.(*Client).DoSigned level=INFO method=GET url=https://seppo.social/demo/apchk.cgi/actor.jsa#main-key requestID=0dc7d70f-753d-44ec-9c5c-1c8e97048399 pubKeyID=https://gotosocial.dev.seppo.social/users/demo/main-key msg="performing request"
Jun  4 10:50:25 vmd32118 gotosocial[53222]: timestamp="2024-06-04T10:50:25.278+02:00" func=server.glob..func1.Logger.func13.1 level=ERROR latency="5.023752519s" userAgent=Seppo.Social method=GET statusCode=500 path=/users/demo clientIP=81.28.232.73 pubKeyID=https://seppo.social/demo/apchk.cgi/actor.jsa#main-key errors="Error #01: callForPubKey: error dereferencing public key https://seppo.social/demo/apchk.cgi/actor.jsa#main-key: Get \"https://seppo.social/demo/apchk.cgi/actor.jsa#main-key\": context deadline exceeded (Client.Timeout exceeded while awaiting headers) (fast fail)\n" requestID=0dc7d70f-753d-44ec-9c5c-1c8e97048399 msg="Internal Server Error: wrote 33B"
```

### What you expected to happen?

a found actor to follow.

### How to reproduce it?

enter @demo@gotosocial.dev.seppo.social into the search input field or use the checker https://seppo.social/demo/apchk.cgi/webfinger?redirect=self&resource=@demo@gotosocial.dev.seppo.social

### Anything else we need to know?

Greetings from @mro@digitalcourage.social, I track it also at https://seppo.social/issues/13

### PR DESCRIPTION
**Pull request by NyaaaWhatsUpDoc**
# Description

~~Marking this as draft for now as i'm not 100% sure how i feel about this fix. Both from a fedi API perspective, and the further complication it adds to our horribly complex (and needing refactoring... again) dereferencer.GetAccount() series of functions :p~~

closes #2961 

## Checklist

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [ ] I/we have made any necessary changes to documentation.
- [ ] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

File: internal/util/punycode.go [hunk 1]
```diff
@@ -73,40 +72,26 @@ func URIMatches(expect *url.URL, uris ...*url.URL) (bool, error) {
...
-func PunifyURIStr(in string) (string, error) {
-	inURI, err := url.Parse(in)
-	if err != nil {
-		return "", err
-	}
-
-	outURIPuny, err := Punify(inURI.Host)
+// PunifyURIToStr returns given URI serialized
+// with the 'host' part converted to punycode.
+func PunifyURIToStr(in *url.URL) (string, error) {
```
Comment (NyaaaWhatsUpDoc) [inline internal/util/punycode.go:87]: this is a tiny performance optimization to reduce needing to allocate a second url.URL object basically

File: internal/util/punycode.go [hunk 2]
```diff
@@ -73,40 +72,26 @@ func URIMatches(expect *url.URL, uris ...*url.URL) (bool, error) {
 // PunifyURI returns a copy of the given URI
 // with the 'host' part converted to punycode.
 func PunifyURI(in *url.URL) (*url.URL, error) {
-	// Take a copy of in.
+	punyHost, err := Punify(in.Host)
```
Comment (NyaaaWhatsUpDoc) [inline internal/util/punycode.go:75]: small performance optimization to not allocate new url.URL unless punify succeeds

**Comment by NyaaaWhatsUpDoc** [comment]
i can confirm that this fixes the issue allowing me to successfully lookup both:
@[demo@dev.seppo.social](mailto:demo@dev.seppo.social)
@[demo@seppo.social](mailto:demo@seppo.social)

**Comment by NyaaaWhatsUpDoc** [comment]
should we decide that this is a suitable fix, we definitely need tests writing to specifically check that a webfinger username doesn't override an AP preferred username. i'm not saying that shouldn't be a possibility in the future (i have no idea what i think about that), but at the moment i'm not sure the codebase is ready for that possibility :p

File: internal/util/punycode.go (hunk 1 above)
Comment (tsmethurst) [reply internal/util/punycode.go:87]: Oh while we're here, one thing I was thinking about was maintaining a ttl cache of translations between punycode and unicode domains, for use inside the Punify and DePunify functions. It's for another PR ofc, just wanted to mention it here before I forget.

**Comment by tsmethurst** [comment]
This looks like a decent fix to me :) We should probably whack some documentation about this in the "federating with GoToSocial" document somewhere, but I can write that if you like.

**Comment by NyaaaWhatsUpDoc** [comment]
> This looks like a decent fix to me :) We should probably whack some documentation about this in the "federating with GoToSocial" document somewhere, but I can write that if you like.

yeah if you could update the docs that would be much appreciated please :) i just pushed a commit that adds a new test for this. feel free to make the docs change on this branch if you'd like

File: internal/util/punycode.go (hunk 1 above)
Comment (NyaaaWhatsUpDoc) [reply internal/util/punycode.go:87]: i think it depends on how compute intensive the punification functions are as to whether this would be worth doing. i haven't really looked too much into them but if it's not much further than URL encode / decode type stuff it might not end up much different compared to the steps of storing things in a hashmap and the dance between concurrent goroutines that is [locking a mutex](https://cs.opensource.google/go/go/+/refs/tags/go1.22.6:src/sync/mutex.go;drc=a71ca3dfbd32faf351ff68bcc26a4d5abd9b06d7;l=117).

**Comment by NyaaaWhatsUpDoc** [comment]
merging this for now to make it easier with some other unrelated work. docs will come in a separate PR :)
