### PR TITLE
[bugfix] Allow unsetting filter expiration dates

### LINKED ISSUE #3497: [bug] sending empty expires_in to filter v2 endpoints sets expiration to now
### Describe the bug with a clear and concise description of what the bug is.

When creating or editing a filter v2, it is not possible to set the duration to indefinite.

### What's your GoToSocial Version?

0.17.2-SNAPSHOT+git-1954ccb

### GoToSocial Arch

goblin.technology

### What happened?

I created a Filter like this:
```
POST https://goblin.technology/api/v2/filters
Content-Type: application/x-www-form-urlencoded
Content-Length: 63
Authorization: Bearer <>
User-Agent: Tusky/26.2-7008c48a Android/13 OkHttp/4.12.0
title=test123&context%5B%5D=home&filter_action=warn&expires_in=
```

I got the following response:
```
{
    "id": "01JBCS3BBG8QJAEQ2XCYTACXPC",
    "title": "test123",
    "context": [
        "home"
    ],
    "expires_at": "2024-10-29T18:37:35.984Z",
    "filter_action": "warn",
    "keywords": [],
    "statuses": []
}
```

As you can see, it has the expiration set to now. 
The same happens when editing the filter with PUT /api/v2/filters

### What you expected to happen?

As per [api docs](https://docs.gotosocial.org/en/latest/api/swagger/) and Mastodon behavior, I would expect the expiration to be indefinite.

### How to reproduce it?

Create or edit a filter.

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by VyrCossont**
# Description

There are two related problems here:
1. handling the empty string, which caused the linked bug; Tobi fixed this for v1 in #3513, but v2 has more optional fields and was handling them differently.
2. handling a literal `null`, which is the correct behavior as far as Mastodon compatibility (I checked); this hasn't led to any *reported* problems yet, and is something Go does not do well.

Fixes #3497

## Checklist

- [x] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [x] I/we have discussed the proposed changes already, either in an issue on the repository, or in the Matrix chat.
- [x] I/we have not leveraged AI to create the proposed changes.
- [x] I/we have performed a self-review of added code.
- [x] I/we have written code that is legible and maintainable by others.
- [x] I/we have commented the added code, particularly in hard-to-understand areas.
- [x] I/we have made any necessary changes to documentation.
- [x] I/we have added tests that cover new code.
- [x] I/we have run tests and they pass locally with the changes.
- [x] I/we have run `go fmt ./...` and `golangci-lint run`.

### CODE REVIEW

File: internal/api/client/filters/v2/filterput.go [hunk 1]
```diff
@@ -180,12 +183,43 @@ func (m *Module) FilterPUTHandler(c *gin.Context) {
 		return
 	}
 
+	// If the request is JSON:
+	// Explicitly check whether `expires_in` is a null literal (vs. not being set at all).
+	hasNullExpiresIn := false
+	if c.ContentType() == gin.MIMEJSON {
```
Comment (NyaaaWhatsUpDoc) [inline internal/api/client/filters/v2/filterput.go:189]: i think you could probably do this more concisely without any of this reading and replacing the reader if you just replaced the `FilterUpdateRequestV2{}.ExpiresIn` field with a `json.RawMessage{}` and then have a `FilterUpdateRequestV2{}.GetExpiresIn()` function that parses the appropriate value :)

**Comment by NyaaaWhatsUpDoc** [comment]
just the one comment but otherwise looking good :)
